---
- name: Copy hello.sh script to Home directory
  copy:
    src: formacioncedei/scripts/hello.sh
    dest: /home/devopsman/hello.sh
    
- name: Update hello.sh permission
  file:
    path: /home/devopsman/hello.sh
    owner: devopsman
    group: devops
    mode: 0755
  
- name: Create keycard file from template  
  template:
    src: templates/keycard.j2
    dest: /home/devopsman/keycard
    owner: devopsman
    group: devops
    mode: "u=rw,g=rw,o=rwx"

- name: Create folder under home directory
  file:
    path: /home/devopsman/unarchive 
    state: directory
    
- name: Install nano editor
  apt:
    name: nano
    state: present
