# Creating three services based on CentOS 7 image built from our Dockerfile

version: '2'

services:

  devopsbox-01:
    #build: .
    image: devopsman/devopsbox:dev
    container_name: devopsbox-01
    volumes:
      - ./ansible:/projects/ansible
    ports:
      - "2211:22"
      - "8081:80"
    networks:
      - devops
    restart: on-failure

  devopsbox-02:
    image: devopsman/devopsbox:dev
    container_name: devopsbox-02
    volumes:
      - ./ansible:/projects/ansible
    ports:
      - "2222:22"
      - "8082:80"
    networks:
      - devops
    restart: on-failure
    depends_on:
      - devopsbox-01

  devopsbox-03:
    image: devopsman/devopsbox:dev
    container_name: devopsbox-03 
    volumes:
      - ./ansible:/projects/ansible
    ports:
      - "2233:22"
      - "8083:80"
    networks:
      - devops
    restart: on-failure
    depends_on:
      - devopsbox-02

networks:
  devops: